services:
  - type: web
    name: mental-health-dashboard
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: DEPLOY_MODE
        value: vercel
      - key: PORT
        value: 8050
    plan: free
